### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by Yuranus** [layumi/Person-reID_GAN#3]
In the ' resnet52_market.m' file, 'etStruct = load('./data/imagenet-resnet-50-dag.mat') ;' makes me so dizzy that I have no clue what to do, is there missing './data'? And when I type 'mkdir data' and after downloading file 'imagenet-resnet-50-dag.mat', then plug back to './data', my Matlab quits working after I run this code immediately! 
And also, where is file 'train_id_net_res_market_gan.m' ?
Thx!

**Comment by layumi** [comment]
@Yuranus 
Sorry for late response. 

1.  Does your Matlab still quit working? Can you load the 'imagenet-resnet-50-dag.mat' directly (double click the file in Matlab GUI)?  It may help you to check whether the file is downloaded correctly. The Res50 model can be download at http://www.vlfeat.org/matconvnet/models/imagenet-resnet-50-dag.mat
In fact, data is a dir for saving and loading model. So it may do no harm to the matlab.

2. The file 'train_id_net_res_market_lsro.m' is the 'train_id_net_res_market_gan.m'
It is the method I used in my paper. But in order to make it clear, I rename the file.
Sorry for my mistake. I will update the Readme.

Any question is welcomed.
