### ISSUE TITLE
How to apply LSRO to verification models?

### ISSUE THREAD

**Issue by tyz1994** [layumi/Person-reID_GAN#7]
When computing verification loss, the last layer's result is [1,0] or [0,1], depending on whether the input images are of the same class.  
I wonder how to handle the following two conditions:
1. Two images are  generated by GAN
2. One image is from the dataset, the other is generated

**Comment by layumi** [comment]
Hi @FlyHighest 
Sorry for late response. 
I will add the training code (for the ident+verif model), and you may check it.
We do not use the generated images for calculating verification loss.
The main reason is too much GAN images in the dataset.
The verification result will always be false (Or be confused at the early time which actually comprise the result). 
Because Generated&Generated image pair should be false match. 
Real& Generated image pair should be false match.

But we still use the generated images for calculating identification loss.

**Comment by tyz1994** [comment]
Thank you for your clarification
